name: Trigger prerelease creation

# This workflow triggers a prerelease creation with changelog and the release notes created by the release toolkit.
# This workflow should be triggered merely from the default branch.
# If you wish to be 100% free creating a prerelease, just create it manually.

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 15 * * 4"

jobs:
  prerelease:
    uses: gsanchezgavier/testGHA/.github/workflows/trigger_prerelease.yaml@main
    secrets:
      bot_token: "${{ secrets.COREINT_BOT_TOKEN }}"
      slack_channel: "fake_channel"
      slack_token: "fake_token"
